services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=165.232.132.113
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://165.232.132.113:5678/
      - N8N_CORS_ALLOW_ORIGIN=*
      - N8N_CORS_ALLOW_CREDENTIALS=true
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_USER_MANAGEMENT_DISABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data: 